### ISSUE TITLE
some confusions about your paper

### ISSUE THREAD

**Issue by leileilin** [Fantabulous-J/Coref-Constituent-Graph#1]
Hello, thank you very much for the great work of open source, but I have some doubts about the main experiment in your paper.
Our baseline + BERT-wwm-base is what?

**Comment by Fantabulous-J** [comment]
Thanks for your interest in our work. **Our baseline + BERT-wwm-base** means the baseline we used on the Ontonotes5.0 Chinese dataset. It's exactly the same as the **Our baseline + SpanBERT-base** in English, except it is initialised from the Chinese BERT-wwm-base model (hfl/chinese-bert-wwm), which can be found in [https://github.com/ymcui/Chinese-BERT-wwm](url)

**Comment by leileilin** [comment]
> Thanks for your interest in our work. **Our baseline + BERT-wwm-base** means the baseline we used on the Ontonotes5.0 Chinese dataset. It's exactly the same as the **Our baseline + SpanBERT-base** in English, except it is initialised from the Chinese BERT-wwm-base model (hfl/chinese-bert-wwm), which can be found in [https://github.com/ymcui/Chinese-BERT-wwm](url)

I mean, is the baseline system proposed in the previous paper? Or is it your new proposal?

**Comment by leileilin** [comment]
> Thanks for your interest in our work. **Our baseline + BERT-wwm-base** means the baseline we used on the Ontonotes5.0 Chinese dataset. It's exactly the same as the **Our baseline + SpanBERT-base** in English, except it is initialised from the Chinese BERT-wwm-base model (hfl/chinese-bert-wwm), which can be found in [https://github.com/ymcui/Chinese-BERT-wwm](url)

And I think your README.md only provides how to train, not how to evaluate and predict the script. Will this one be provided?

**Comment by leileilin** [comment]
And your environment has conflicts between packages.
